In [4]:
import pandas as pd
import os
import numpy as np
import scipy as sp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC,SVC
%matplotlib inline


# Lista de arquivos ossos original (sem desmineralização)
lista_arq_ossos=os.listdir('Dados/original/')
# Lista de arquivos ossos desmineralização 1
lista_arq_desm1=os.listdir('Dados/desm1/')
# Lista de arquivos ossos desmineralização 2
lista_arq_desm2=os.listdir('Dados/desm2/')
# Lista de arquivos ossos desmineralização 3
lista_arq_desm3=os.listdir('Dados/desm3/')

# Quantidade total de sinais
total_signal = len(lista_arq_ossos)+len(lista_arq_desm1)+len(lista_arq_desm2)+len(lista_arq_desm3)+1
# Matriz zerada para comportar todos os sinais
ossos = np.zeros((total_signal,15997))
# Matriz zerada para comportar todas as classes
classes = np.zeros((total_signal))

data_len = 15999

# Lendo os sinais de ossos sem desmineralização
i=0
# Lendo os sinais de ossos desmineralização 1
for nome2 in lista_arq_desm1:
    arq = open('Dados/desm1/'+nome2,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 1
    i = i+1
    data=0
    arq.close()

for nome3 in lista_arq_desm2:
    arq = open('Dados/desm2/'+nome3,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 2
    i = i+1
    data=0
    arq.close()



for nome4 in lista_arq_desm3:
    arq = open('Dados/desm3/'+nome4,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 3
    i = i+1
    data=0
    arq.close()
time = []
for i in range(1,16001):
    time.append(i*2e-8)
ossos = ossos[0:i,:]
classes = classes[0:i]
ossos_df = pd.DataFrame(ossos)
classes_df= pd.DataFrame(classes)
classes_df['Desm'] = classes_df[0]
classes_df = classes_df.drop(0,axis=1)
result = pd.concat([ossos_df, classes_df], axis=1, sort=False)
result

0         1         2         3        4        5        6  \
0    -0.000150 -0.000150 -0.000150 -0.000150 -0.00015 -0.00015 -0.00015   
1    -0.000100 -0.000100 -0.000100 -0.000100 -0.00010 -0.00010 -0.00010   
2    -0.000100 -0.000100 -0.000100 -0.000100 -0.00010 -0.00010 -0.00010   
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.00020 -0.00020 -0.00020   
4    -0.000039 -0.000039 -0.000039 -0.000039 -0.00020 -0.00020 -0.00020   
...        ...       ...       ...       ...      ...      ...      ...   
1654  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1655  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1656  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1657  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1658  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   

            7        8        9  ...     15988     15989     15990     15991  \
0    -0.00015 -0.00015 -0.00015  ... -0.000391 -0.000391 -0.000391 -0.000271   
1    -0.00010 -0.00010 -0.00010  ... -0.000422 -0.000422 -0.000422 -0.000422   
2    -0.00010 -0.00010 -0.00010  ... -0.000582 -0.000743 -0.000743 -0.000743   
3    -0.00020 -0.00020 -0.00020  ... -0.000200 -0.000200 -0.000200 -0.000200   
4    -0.00020 -0.00020 -0.00020  ...  0.000282  0.000282  0.000282  0.000282   
...       ...      ...      ...  ...       ...       ...       ...       ...   
1654  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1655  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1656  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1657  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1658  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   

         15992     15993     15994     15995     15996  Desm  
0    -0.000271 -0.000271 -0.000271 -0.000271 -0.000271   1.0  
1    -0.000422 -0.000422 -0.000422 -0.000422 -0.000422   1.0  
2    -0.000743 -0.000743 -0.000743 -0.000743 -0.000743   1.0  
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   1.0  
4     0.000282  0.000282  0.000122  0.000282  0.000282   1.0  
...        ...       ...       ...       ...       ...   ...  
1654  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1655  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1656  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1657  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1658  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  

[1659 rows x 15998 columns]

In [13]:
ossos_df.iloc[0,:]

0       -0.000150
1       -0.000150
2       -0.000150
3       -0.000150
4       -0.000150
           ...   
15992   -0.000271
15993   -0.000271
15994   -0.000271
15995   -0.000271
15996   -0.000271
Name: 0, Length: 15997, dtype: float64

In [87]:
clf = SVC(gamma='scale', decision_function_shape='ovo')
X = result.drop(['Desm'],axis=1)
y = result['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train,y_train) 
pred_clf = clf.predict(X_test)
print(classification_report(y_test, pred_clf))
cm_clf= confusion_matrix(y_test, pred_clf)
print(cm_clf)

              precision    recall  f1-score   support

         1.0       0.55      0.55      0.55        83
         2.0       0.61      0.48      0.54       154
         3.0       0.62      0.79      0.69       122

    accuracy                           0.60       359
   macro avg       0.60      0.61      0.60       359
weighted avg       0.60      0.60      0.59       359

[[46 29  8]
 [29 74 51]
 [ 8 18 96]]
