In [6]:
import pandas as pd
import os
import numpy as np
import scipy as sp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC,SVC
%matplotlib inline

In [8]:



# Lista de arquivos ossos original (sem desmineralização)
lista_arq_ossos=os.listdir('Dados/original/')
# Lista de arquivos ossos desmineralização 1
lista_arq_desm1=os.listdir('Dados/desm1/')
# Lista de arquivos ossos desmineralização 2
lista_arq_desm2=os.listdir('Dados/desm2/')
# Lista de arquivos ossos desmineralização 3
lista_arq_desm3=os.listdir('Dados/desm3/')

# Quantidade total de sinais
total_signal = len(lista_arq_ossos)+len(lista_arq_desm1)+len(lista_arq_desm2)+len(lista_arq_desm3)+1
# Matriz zerada para comportar todos os sinais
ossos = np.zeros((total_signal,15997))
# Matriz zerada para comportar todas as classes
classes = np.zeros((total_signal))

data_len = 15999

# Lendo os sinais de ossos sem desmineralização
i=0
# Lendo os sinais de ossos desmineralização 1
for nome2 in lista_arq_desm1:
    arq = open('Dados/desm1/'+nome2,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 1
    i = i+1
    data=0
    arq.close()

for nome3 in lista_arq_desm2:
    arq = open('Dados/desm2/'+nome3,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 2
    i = i+1
    data=0
    arq.close()



for nome4 in lista_arq_desm3:
    arq = open('Dados/desm3/'+nome4,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    ossos[i,:]=data
    classes[i] = 3
    i = i+1
    data=0
    arq.close()
time = []
for i in range(1,16001):
    time.append(i*2e-8)
ossos = ossos[0:i,:]
classes = classes[0:i]
ossos_df = pd.DataFrame(ossos)
classes_df= pd.DataFrame(classes)
classes_df['Desm'] = classes_df[0]
classes_df = classes_df.drop(0,axis=1)
result = pd.concat([ossos_df, classes_df], axis=1, sort=False)
result

0         1         2         3        4        5        6  \
0    -0.000150 -0.000150 -0.000150 -0.000150 -0.00015 -0.00015 -0.00015   
1    -0.000100 -0.000100 -0.000100 -0.000100 -0.00010 -0.00010 -0.00010   
2    -0.000100 -0.000100 -0.000100 -0.000100 -0.00010 -0.00010 -0.00010   
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.00020 -0.00020 -0.00020   
4    -0.000039 -0.000039 -0.000039 -0.000039 -0.00020 -0.00020 -0.00020   
...        ...       ...       ...       ...      ...      ...      ...   
1654  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1655  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1656  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1657  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   
1658  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000  0.00000   

            7        8        9  ...     15988     15989     15990     15991  \
0    -0.00015 -0.00015 -0.00015  ... -0.000391 -0.000391 -0.000391 -0.000271   
1    -0.00010 -0.00010 -0.00010  ... -0.000422 -0.000422 -0.000422 -0.000422   
2    -0.00010 -0.00010 -0.00010  ... -0.000582 -0.000743 -0.000743 -0.000743   
3    -0.00020 -0.00020 -0.00020  ... -0.000200 -0.000200 -0.000200 -0.000200   
4    -0.00020 -0.00020 -0.00020  ...  0.000282  0.000282  0.000282  0.000282   
...       ...      ...      ...  ...       ...       ...       ...       ...   
1654  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1655  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1656  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1657  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   
1658  0.00000  0.00000  0.00000  ...  0.000000  0.000000  0.000000  0.000000   

         15992     15993     15994     15995     15996  Desm  
0    -0.000271 -0.000271 -0.000271 -0.000271 -0.000271   1.0  
1    -0.000422 -0.000422 -0.000422 -0.000422 -0.000422   1.0  
2    -0.000743 -0.000743 -0.000743 -0.000743 -0.000743   1.0  
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   1.0  
4     0.000282  0.000282  0.000122  0.000282  0.000282   1.0  
...        ...       ...       ...       ...       ...   ...  
1654  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1655  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1656  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1657  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  
1658  0.000000  0.000000  0.000000  0.000000  0.000000   0.0  

[1659 rows x 15998 columns]

In [13]:
classes_df.iloc[900,:]

Desm    3.0
Name: 900, dtype: float64

In [3]:
clf = SVC(gamma='scale', decision_function_shape='ovo')
X = result.drop(['Desm'],axis=1)
y = result['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train,y_train) 
pred_clf = clf.predict(X_test)
print(classification_report(y_test, pred_clf))
cm_clf= confusion_matrix(y_test, pred_clf)
print(cm_clf)

              precision    recall  f1-score   support

         0.0       0.90      1.00      0.95       130
         1.0       0.51      0.41      0.46        97
         2.0       0.43      0.50      0.47       137
         3.0       0.70      0.61      0.65       134

    accuracy                           0.64       498
   macro avg       0.64      0.63      0.63       498
weighted avg       0.64      0.64      0.64       498

[[130   0   0   0]
 [  4  40  50   3]
 [  7  29  69  32]
 [  3   9  40  82]]


In [26]:
X = result[result['Desm']!= 0].drop(['Desm'],axis=1)
y = result[result['Desm']!= 0]['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X_train)
pred_kmeans = kmeans.predict(X_test)
print(classification_report(y_test, pred_kmeans))
cm_kmeans= confusion_matrix(y_test, pred_kmeans)
print(cm_kmeans)

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         0
         1.0       0.29      0.98      0.45       102
         2.0       0.47      0.06      0.10       125
         3.0       0.00      0.00      0.00       132

    accuracy                           0.30       359
   macro avg       0.19      0.26      0.14       359
weighted avg       0.25      0.30      0.16       359

[[  0   0   0   0]
 [  0 100   2   0]
 [  3 115   7   0]
 [  0 126   6   0]]


c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [18]:
result[result['Desm']!= 0]

0         1         2         3         4         5         6  \
0    -0.000150 -0.000150 -0.000150 -0.000150 -0.000150 -0.000150 -0.000150   
1    -0.000100 -0.000100 -0.000100 -0.000100 -0.000100 -0.000100 -0.000100   
2    -0.000100 -0.000100 -0.000100 -0.000100 -0.000100 -0.000100 -0.000100   
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   
4    -0.000039 -0.000039 -0.000039 -0.000039 -0.000200 -0.000200 -0.000200   
...        ...       ...       ...       ...       ...       ...       ...   
1191 -0.000307 -0.000307 -0.000307 -0.000307 -0.000307 -0.000187 -0.000187   
1192 -0.000127 -0.000127 -0.000127 -0.000127 -0.000127 -0.000127 -0.000127   
1193 -0.000277 -0.000277 -0.000277 -0.000277 -0.000277 -0.000277 -0.000277   
1194 -0.000054 -0.000054 -0.000054 -0.000054 -0.000215 -0.000215 -0.000215   
1195 -0.000385 -0.000385 -0.000385 -0.000546 -0.000546 -0.000546 -0.000385   

             7         8         9  ...     15988     15989     15990  \
0    -0.000150 -0.000150 -0.000150  ... -0.000391 -0.000391 -0.000391   
1    -0.000100 -0.000100 -0.000100  ... -0.000422 -0.000422 -0.000422   
2    -0.000100 -0.000100 -0.000100  ... -0.000582 -0.000743 -0.000743   
3    -0.000200 -0.000200 -0.000200  ... -0.000200 -0.000200 -0.000200   
4    -0.000200 -0.000200 -0.000200  ...  0.000282  0.000282  0.000282   
...        ...       ...       ...  ...       ...       ...       ...   
1191 -0.000066 -0.000066 -0.000066  ... -0.001152 -0.001152 -0.001152   
1192 -0.000127 -0.000127 -0.000127  ... -0.000328 -0.000328 -0.000328   
1193 -0.000277 -0.000156 -0.000277  ... -0.001483 -0.001483 -0.001483   
1194 -0.000215 -0.000215 -0.000215  ... -0.001340 -0.001340 -0.001340   
1195 -0.000385 -0.000385 -0.000385  ... -0.000546 -0.000385 -0.000385   

         15991     15992     15993     15994     15995     15996  Desm  
0    -0.000271 -0.000271 -0.000271 -0.000271 -0.000271 -0.000271   1.0  
1    -0.000422 -0.000422 -0.000422 -0.000422 -0.000422 -0.000422   1.0  
2    -0.000743 -0.000743 -0.000743 -0.000743 -0.000743 -0.000743   1.0  
3    -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   1.0  
4     0.000282  0.000282  0.000282  0.000122  0.000282  0.000282   1.0  
...        ...       ...       ...       ...       ...       ...   ...  
1191 -0.001031 -0.001031 -0.001031 -0.001031 -0.001031 -0.001152   3.0  
1192 -0.000328 -0.000328 -0.000328 -0.000328 -0.000529 -0.000328   3.0  
1193 -0.001483 -0.001362 -0.001362 -0.001362 -0.001483 -0.001483   3.0  
1194 -0.001340 -0.001340 -0.001340 -0.001340 -0.001340 -0.001340   3.0  
1195 -0.000385 -0.000546 -0.000385 -0.000385 -0.000385 -0.000385   3.0  

[1196 rows x 15998 columns]