In [5]:
import pandas as pd
import os
import numpy as np


# Lista de arquivos ossos original (sem desmineralização)
lista_arq_ossos=os.listdir('CNN_osso/original/')
# Lista de arquivos ossos desmineralização 1
lista_arq_desm1=os.listdir('CNN_osso/desm1/')
# Lista de arquivos ossos desmineralização 2
lista_arq_desm2=os.listdir('CNN_osso/desm2/')
# Lista de arquivos ossos desmineralização 3
lista_arq_desm3=os.listdir('CNN_osso/desm3/')

# Quantidade total de sinais
total_signal = len(lista_arq_ossos)+len(lista_arq_desm1)+len(lista_arq_desm2)+len(lista_arq_desm3)+1

# Matriz zerada para comportar todos os sinais
ossos = np.zeros((total_signal,15997))
# Matriz zerada para comportar todas as classes
classes = np.zeros((total_signal))

data_len = 15999

# Lendo os sinais de ossos sem desmineralização
i=0
# Lendo os sinais de ossos desmineralização 1
for nome2 in lista_arq_desm1:
	arq = open('CNN_osso/desm1/'+nome2,'r')
	data = arq.readlines()
	data = [float(x) for x in data]
	data = data [2:data_len]
	ossos[i,:]=data
#	classes[i,:] = [0., 1., 0., 0.]
	classes[i] = 1
	i = i+1
	data=0
	arq.close()

# Lendo os sinais de ossos desmineralização 2
for nome3 in lista_arq_desm2:
	arq = open('CNN_osso/desm2/'+nome3,'r')
	data = arq.readlines()
	data = [float(x) for x in data]
	data = data [2:data_len]
	ossos[i,:]=data
#	classes[i,:] = [0., 0., 1., 0.]
	classes[i] = 2
	i = i+1
	data=0
	arq.close()

# Lendo os sinais de ossos desmineralização 3
for nome4 in lista_arq_desm3:
	arq = open('CNN_osso/desm3/'+nome4,'r')
	data = arq.readlines()
	data = [float(x) for x in data]
	data = data [2:data_len]
	ossos[i,:]=data
#	classes[i,:] = [0., 0., 0., 1.]
	classes[i] = 3
	i = i+1
	data=0
	arq.close()

ossos = ossos[0:i,:]
classes = classes[0:i]


In [38]:
ossos_df = pd.DataFrame(ossos)
classes_df= pd.DataFrame(classes)
classes_df['Desm'] = classes_df[0]
classes_df = classes_df.drop(0,axis=1)
ossos_df

0         1         2         3         4         5         6      \
0    0.000118  0.000118  0.000118  0.000118  0.000118 -0.000043 -0.000043   
1   -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   
2   -0.000236 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075   
3   -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218   
4   -0.000028 -0.000189 -0.000028 -0.000028 -0.000028 -0.000028 -0.000028   
..        ...       ...       ...       ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489   
296 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000061 -0.000061   
297 -0.000187 -0.000187 -0.000388 -0.000388 -0.000388 -0.000388 -0.000388   
298 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   
299 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   

        7         8         9      ...     15987     15988     15989  \
0   -0.000043 -0.000043 -0.000043  ...  0.000118  0.000118  0.000118   
1   -0.000200 -0.000200 -0.000079  ...  0.000041  0.000041  0.000041   
2   -0.000075 -0.000075 -0.000075  ... -0.000236 -0.000236 -0.000236   
3   -0.000218 -0.000218 -0.000218  ...  0.000426  0.000426  0.000426   
4   -0.000028 -0.000028 -0.000028  ... -0.000511 -0.000511 -0.000511   
..        ...       ...       ...  ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489  ...  0.000154 -0.000007 -0.000007   
296 -0.000222 -0.000222 -0.000222  ... -0.000704 -0.000704 -0.000704   
297 -0.000187 -0.000187 -0.000187  ...  0.000014  0.000014  0.000014   
298 -0.000222 -0.000222 -0.000222  ... -0.000061 -0.000061  0.000100   
299 -0.000222 -0.000222 -0.000222  ...  0.000100  0.000100  0.000100   

        15990     15991     15992     15993     15994     15995     15996  
0    0.000118  0.000118  0.000118  0.000118  0.000118  0.000118  0.000118  
1    0.000041 -0.000079  0.000041 -0.000079  0.000041  0.000041  0.000041  
2   -0.000236 -0.000236 -0.000236 -0.000236 -0.000236 -0.000075 -0.000075  
3    0.000426  0.000426  0.000426  0.000426  0.000426  0.000426  0.000426  
4   -0.000511 -0.000511 -0.000511 -0.000511 -0.000511 -0.000672 -0.000672  
..        ...       ...       ...       ...       ...       ...       ...  
295 -0.000007 -0.000007 -0.000168 -0.000007 -0.000007 -0.000007 -0.000168  
296 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704  
297  0.000014  0.000014  0.000014  0.000014  0.000014  0.000014  0.000014  
298  0.000100  0.000100  0.000100  0.000100  0.000100  0.000100  0.000100  
299  0.000100  0.000100  0.000100  0.000100  0.000100 -0.000061 -0.000061  

[300 rows x 15997 columns]

In [35]:
result = pd.concat([ossos_df, classes_df], axis=1, sort=False)
result

0         1         2         3         4         5         6  \
0    0.000118  0.000118  0.000118  0.000118  0.000118 -0.000043 -0.000043   
1   -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   
2   -0.000236 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075   
3   -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218   
4   -0.000028 -0.000189 -0.000028 -0.000028 -0.000028 -0.000028 -0.000028   
..        ...       ...       ...       ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489   
296 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000061 -0.000061   
297 -0.000187 -0.000187 -0.000388 -0.000388 -0.000388 -0.000388 -0.000388   
298 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   
299 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   

            7         8         9  ...     15988     15989     15990  \
0   -0.000043 -0.000043 -0.000043  ...  0.000118  0.000118  0.000118   
1   -0.000200 -0.000200 -0.000079  ...  0.000041  0.000041  0.000041   
2   -0.000075 -0.000075 -0.000075  ... -0.000236 -0.000236 -0.000236   
3   -0.000218 -0.000218 -0.000218  ...  0.000426  0.000426  0.000426   
4   -0.000028 -0.000028 -0.000028  ... -0.000511 -0.000511 -0.000511   
..        ...       ...       ...  ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489  ... -0.000007 -0.000007 -0.000007   
296 -0.000222 -0.000222 -0.000222  ... -0.000704 -0.000704 -0.000704   
297 -0.000187 -0.000187 -0.000187  ...  0.000014  0.000014  0.000014   
298 -0.000222 -0.000222 -0.000222  ... -0.000061  0.000100  0.000100   
299 -0.000222 -0.000222 -0.000222  ...  0.000100  0.000100  0.000100   

        15991     15992     15993     15994     15995     15996  Desm  
0    0.000118  0.000118  0.000118  0.000118  0.000118  0.000118   1.0  
1   -0.000079  0.000041 -0.000079  0.000041  0.000041  0.000041   1.0  
2   -0.000236 -0.000236 -0.000236 -0.000236 -0.000075 -0.000075   1.0  
3    0.000426  0.000426  0.000426  0.000426  0.000426  0.000426   1.0  
4   -0.000511 -0.000511 -0.000511 -0.000511 -0.000672 -0.000672   1.0  
..        ...       ...       ...       ...       ...       ...   ...  
295 -0.000007 -0.000168 -0.000007 -0.000007 -0.000007 -0.000168   3.0  
296 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704   3.0  
297  0.000014  0.000014  0.000014  0.000014  0.000014  0.000014   3.0  
298  0.000100  0.000100  0.000100  0.000100  0.000100  0.000100   3.0  
299  0.000100  0.000100  0.000100  0.000100 -0.000061 -0.000061   3.0  

[300 rows x 15998 columns]

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.svm import SVC
%matplotlib inline

In [375]:
X = result.drop(['Desm'],axis=1)
y = result['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
pred_lr = lr_model.predict(X_test)
print(classification_report(y_test, pred_lr))
cm_lr= confusion_matrix(y_test, pred_lr)
cm_lr


c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


              precision    recall  f1-score   support

         1.0       0.43      0.09      0.16        95
         2.0       0.42      0.70      0.52       141
         3.0       0.59      0.49      0.54       123

    accuracy                           0.47       359
   macro avg       0.48      0.43      0.40       359
weighted avg       0.48      0.47      0.43       359



array([[ 9, 78,  8],
       [ 9, 99, 33],
       [ 3, 60, 60]], dtype=int64)

In [381]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
pred_knn = knn.predict(X_test)
print(classification_report(y_test, pred_knn))
cm_knn= confusion_matrix(y_test, pred_knn)
cm_knn

              precision    recall  f1-score   support

         1.0       0.51      0.40      0.45        95
         2.0       0.40      0.54      0.46       141
         3.0       0.48      0.37      0.42       123

    accuracy                           0.45       359
   macro avg       0.46      0.44      0.44       359
weighted avg       0.46      0.45      0.44       359



array([[38, 47, 10],
       [25, 76, 40],
       [12, 65, 46]], dtype=int64)

In [ ]:
error_rate = []

# Levará algum tempo
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    error_rate.append(np.mean(pred_i != y_test))

plt.figure(figsize=(10,6))
plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

In [194]:
X_train=list(X_train)
y_train=list(y_train)

In [195]:
neigh = KNeighborsClassifier(algorithm='auto')
neigh.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [189]:
print(classification_report(y_test, predictions))


1128    [-0.000175, -0.000175, -0.000175, -0.000175, -...
165     [-5e-05, -5e-05, -5e-05, -5e-05, -5e-05, -5e-0...
746     [-0.000169221, -0.000169221, -0.000169221, -0....
385     [0.000166206, -7.5e-05, -7.5e-05, -7.5e-05, -7...
865     [-0.000321608, 0.0, 0.0, 0.0, 0.0, 0.0, -0.000...
                              ...                        
793     [-1.809e-05, -1.809e-05, -1.809e-05, -1.809e-0...
117     [-0.00015201, -0.00015201, -0.00015201, -0.000...
544     [0.000217588, 0.000217588, 0.000217588, 0.0002...
222     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1116    [0.0, 0.0, 0.0, -0.00040201, -0.00040201, 0.0,...
Name: Sinais, Length: 359, dtype: object

In [196]:
ossos_df.iloc[713,0]

array([-0.00020678, -0.00020678, -0.00036759, ...,  0.00124045,
        0.00124045,  0.00107965])

In [1]:
neigh.predict_proba([ossos_df.iloc[713,0]])

NameError: name 'neigh' is not defined

In [37]:
clf = SVC(gamma = 'scale',decision_function_shape='ovo',C=100)
X = result.drop(['Desm'],axis=1)
y = result['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train,y_train) 
pred_clf = clf.predict(X_test)
print(classification_report(y_test, pred_clf))
cm_clf= confusion_matrix(y_test, pred_clf)
print(cm_clf)
result

              precision    recall  f1-score   support

         1.0       0.50      0.54      0.52        28
         2.0       0.43      0.30      0.36        33
         3.0       0.49      0.62      0.55        29

    accuracy                           0.48        90
   macro avg       0.47      0.49      0.47        90
weighted avg       0.47      0.48      0.47        90

[[15  8  5]
 [ 9 10 14]
 [ 6  5 18]]


0         1         2         3         4         5         6  \
0    0.000118  0.000118  0.000118  0.000118  0.000118 -0.000043 -0.000043   
1   -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200 -0.000200   
2   -0.000236 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075 -0.000075   
3   -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218 -0.000218   
4   -0.000028 -0.000189 -0.000028 -0.000028 -0.000028 -0.000028 -0.000028   
..        ...       ...       ...       ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489 -0.000489   
296 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000061 -0.000061   
297 -0.000187 -0.000187 -0.000388 -0.000388 -0.000388 -0.000388 -0.000388   
298 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   
299 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222 -0.000222   

            7         8         9  ...     15988     15989     15990  \
0   -0.000043 -0.000043 -0.000043  ...  0.000118  0.000118  0.000118   
1   -0.000200 -0.000200 -0.000079  ...  0.000041  0.000041  0.000041   
2   -0.000075 -0.000075 -0.000075  ... -0.000236 -0.000236 -0.000236   
3   -0.000218 -0.000218 -0.000218  ...  0.000426  0.000426  0.000426   
4   -0.000028 -0.000028 -0.000028  ... -0.000511 -0.000511 -0.000511   
..        ...       ...       ...  ...       ...       ...       ...   
295 -0.000489 -0.000489 -0.000489  ... -0.000007 -0.000007 -0.000007   
296 -0.000222 -0.000222 -0.000222  ... -0.000704 -0.000704 -0.000704   
297 -0.000187 -0.000187 -0.000187  ...  0.000014  0.000014  0.000014   
298 -0.000222 -0.000222 -0.000222  ... -0.000061  0.000100  0.000100   
299 -0.000222 -0.000222 -0.000222  ...  0.000100  0.000100  0.000100   

        15991     15992     15993     15994     15995     15996  Desm  
0    0.000118  0.000118  0.000118  0.000118  0.000118  0.000118   1.0  
1   -0.000079  0.000041 -0.000079  0.000041  0.000041  0.000041   1.0  
2   -0.000236 -0.000236 -0.000236 -0.000236 -0.000075 -0.000075   1.0  
3    0.000426  0.000426  0.000426  0.000426  0.000426  0.000426   1.0  
4   -0.000511 -0.000511 -0.000511 -0.000511 -0.000672 -0.000672   1.0  
..        ...       ...       ...       ...       ...       ...   ...  
295 -0.000007 -0.000168 -0.000007 -0.000007 -0.000007 -0.000168   3.0  
296 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704 -0.000704   3.0  
297  0.000014  0.000014  0.000014  0.000014  0.000014  0.000014   3.0  
298  0.000100  0.000100  0.000100  0.000100  0.000100  0.000100   3.0  
299  0.000100  0.000100  0.000100  0.000100 -0.000061 -0.000061   3.0  

[300 rows x 15998 columns]

In [17]:
cm_clf

array([[40, 50,  9],
       [14, 80, 35],
       [ 7, 53, 71]], dtype=int64)

In [ ]:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovo', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
dec = clf.decision_function([[1.0]])
clf.decision_function_shape = "ovr"
dec = clf.decision_function([[1.0]])
dec