In [83]:
import pandas as pd
import os
import numpy as np
import scipy as sp
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.svm import LinearSVC,SVC
%matplotlib inline


# Lista de arquivos ossos original (sem desmineralização)
lista_arq_ossos=os.listdir('Dados/original/')
# Lista de arquivos ossos desmineralização 1
lista_arq_desm1=os.listdir('Dados/desm1/')
# Lista de arquivos ossos desmineralização 2
lista_arq_desm2=os.listdir('Dados/desm2/')
# Lista de arquivos ossos desmineralização 3
lista_arq_desm3=os.listdir('Dados/desm3/')

# Quantidade total de sinais
total_signal = len(lista_arq_ossos)+len(lista_arq_desm1)+len(lista_arq_desm2)+len(lista_arq_desm3)+1
# Matriz zerada para comportar todos os sinais
ossos = np.zeros((total_signal,15997))
# Matriz zerada para comportar todas as classes
classes = np.zeros((total_signal))

data_len = 15999

# Lendo os sinais de ossos sem desmineralização
i=0
# Lendo os sinais de ossos desmineralização 1
for nome2 in lista_arq_desm1:
    arq = open('Dados/desm1/'+nome2,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    data_fft = sp.fft(data)
    ossos[i,:]=data_fft
    classes[i] = 1
    i = i+1
    data=0
    arq.close()

for nome3 in lista_arq_desm2:
    arq = open('Dados/desm2/'+nome3,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    data_fft = sp.fft(data)
    ossos[i,:]=data_fft
    classes[i] = 2
    i = i+1
    data=0
    arq.close()



for nome4 in lista_arq_desm3:
    arq = open('Dados/desm3/'+nome4,'r')
    data = arq.readlines()
    data = [float(x) for x in data]
    data = data [2:data_len]
    data = np.array(data)
    data_fft = sp.fft(data)
    ossos[i,:]=data_fft
    classes[i] = 3
    i = i+1
    data=0
    arq.close()

ossos = ossos[0:i,:]
classes = classes[0:i]
ossos_df = pd.DataFrame(ossos)
classes_df= pd.DataFrame(classes)
classes_df['Desm'] = classes_df[0]
classes_df = classes_df.drop(0,axis=1)
result = pd.concat([ossos_df, classes_df], axis=1, sort=False)
result

c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:42: ComplexWarning: Casting complex values to real discards the imaginary part
c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:55: ComplexWarning: Casting complex values to real discards the imaginary part
c:\users\lucas\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:70: ComplexWarning: Casting complex values to real discards the imaginary part


0         1         2         3         4         5         6  \
0    -1.150344  0.034483 -1.295305 -0.752226  1.395737  2.059646  0.429726   
1    -1.321991 -0.577669 -0.025458  1.085847 -1.297116 -0.736558 -0.093157   
2    -1.264263 -0.274360 -1.471947  0.377061  1.376285 -0.998327 -0.704878   
3    -1.505008  0.113451 -1.276847 -0.670367  1.793778  2.826594  1.317305   
4    -1.720486 -0.060335 -1.182691  0.536869  2.274193  0.637405 -0.372501   
...        ...       ...       ...       ...       ...       ...       ...   
1191 -4.638956  0.001170 -2.467294 -1.846255 -2.170049  0.678737  4.139917   
1192 -3.220925 -0.678009  4.408197  1.530833 -5.754421 -4.653909  2.101481   
1193 -4.319047  0.175976 -0.309516  0.234778 -0.652063 -1.058688 -0.904428   
1194 -5.039595 -0.368846 -2.308880 -2.340707 -2.768340 -0.359363  3.813306   
1195 -5.909359 -1.056797  3.186583  6.756253 -2.205455 -6.466189 -5.557061   

             7         8         9  ...     15988     15989     15990  \
0    -0.190083 -1.138217 -1.686360  ... -1.686360 -1.138217 -0.190083   
1     0.855367 -0.274501 -0.908924  ... -0.908924 -0.274501  0.855367   
2    -0.981188 -1.779436  0.234845  ...  0.234845 -1.779436 -0.981188   
3    -0.209482 -1.582511 -2.404017  ... -2.404017 -1.582511 -0.209482   
4    -0.454698 -1.001125  0.588555  ...  0.588555 -1.001125 -0.454698   
...        ...       ...       ...  ...       ...       ...       ...   
1191  3.602424 -1.032184 -2.203874  ... -2.203874 -1.032184  3.602424   
1192  2.832672  3.048103  3.612888  ...  3.612888  3.048103  2.832672   
1193  0.066541  1.153644  2.672455  ...  2.672455  1.153644  0.066541   
1194  3.798612  1.998467 -1.647487  ... -1.647487  1.998467  3.798612   
1195 -0.952528  1.318215  1.811680  ...  1.811680  1.318215 -0.952528   

         15991     15992     15993     15994     15995     15996  Desm  
0     0.429726  2.059646  1.395737 -0.752226 -1.295305  0.034483   1.0  
1    -0.093157 -0.736558 -1.297116  1.085847 -0.025458 -0.577669   1.0  
2    -0.704878 -0.998327  1.376285  0.377061 -1.471947 -0.274360   1.0  
3     1.317305  2.826594  1.793778 -0.670367 -1.276847  0.113451   1.0  
4    -0.372501  0.637405  2.274193  0.536869 -1.182691 -0.060335   1.0  
...        ...       ...       ...       ...       ...       ...   ...  
1191  4.139917  0.678737 -2.170049 -1.846255 -2.467294  0.001170   3.0  
1192  2.101481 -4.653909 -5.754421  1.530833  4.408197 -0.678009   3.0  
1193 -0.904428 -1.058688 -0.652063  0.234778 -0.309516  0.175976   3.0  
1194  3.813306 -0.359363 -2.768340 -2.340707 -2.308880 -0.368846   3.0  
1195 -5.557061 -6.466189 -2.205455  6.756253  3.186583 -1.056797   3.0  

[1196 rows x 15998 columns]

In [87]:
clf = SVC(gamma='scale', decision_function_shape='ovo')
X = result.drop(['Desm'],axis=1)
y = result['Desm']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
clf.fit(X_train,y_train) 
pred_clf = clf.predict(X_test)
print(classification_report(y_test, pred_clf))
cm_clf= confusion_matrix(y_test, pred_clf)
print(cm_clf)

              precision    recall  f1-score   support

         1.0       0.55      0.55      0.55        83
         2.0       0.61      0.48      0.54       154
         3.0       0.62      0.79      0.69       122

    accuracy                           0.60       359
   macro avg       0.60      0.61      0.60       359
weighted avg       0.60      0.60      0.59       359

[[46 29  8]
 [29 74 51]
 [ 8 18 96]]
